b1f5/coding-test-study

- programmers/level0/겹치는-선분의-길이/이춘구.js
- programmers/level0/다항식-더하기/이춘구.js
- programmers/level0/분수의-덧셈/이춘구.js
- programmers/level0/안전지대/이춘구.js
- programmers/level0/옹알이/이춘구.js
- programmers/level0/저주의-숫자-3/이춘구.js
- programmers/level0/평행/이춘구.js
> 과거 풀이 이력 + 저주의 숫자 3

- programmers/level0/OX퀴즈/곽성재.js
- eval 없이 풀이 했습니다.
- 연산결과와 주어지는 값과 비교할 때, 굳이 parseInt없이 자바스크립트 특성을 활용했습니다.
> ✨ OX퀴즈-1차풀이

- programmers/level0/OX퀴즈/김은경.js
- programmers/level0/저주의-숫자3/김은경.js
> the first pull request

- woowacourse-precourse/javascript-onboarding/week1/PROBLEM1/곽성재.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM2/곽성재.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM3/곽성재.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM4/곽성재.js
문제 1은 기능별로 분리를 해봤습니다.
문제 2는 정규식으로 풀었습니다.
문제 3은 이중반복문으로 카운트를 더했습니다.
문제 4는 charCode말고 다르게 풀었습니다.
npm test  해보니, 우테코에서 테케로 넣어둔건 패스 하는 모양입니다!
문제 자체를 풀기만하는게 목적이 아니어서 전체적으로 시간이 좀 많이 걸렸습니다.
> 문제 1 ~ 4 해결

- woowacourse-precourse/javascript-onboarding/week1/PROBLEM5/곽성재.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM6/곽성재.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM7/곽성재.js
일부 주석이 있는데, 이는 최종적으로는 없앨 예정이나 지금은 코드 확인을 위하여 남겨두었습니다.
> 문제 5 ~ 7 해결 코드입니다.

- woowacourse-precourse/javascript-onboarding/week1/PROBLEM1/전세원.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM2/전세원.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM3/전세원.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM4/전세원.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM5/전세원.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM6/전세원.js
- woowacourse-precourse/javascript-onboarding/week1/PROBLEM7/전세원.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/.gitignore
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/.npmrc
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/README.md
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/__tests__/ApplicationTest.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/__tests__/StringTest.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/package-lock.json
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/package.json
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball-main/src/App.js
문제 1은 합하고 곱하는 함수를 따로 만들어서 계산하는 함수에 넣어주었고, 최종 solution 함수에서는 조건식에 따라 결과만 나올 수 있게 작성하였습니다. 
문제 2는 solution 함수안에 check라는 함수를 만들어 정규식으로 연속하는 글자가 있으면 replace되게 만들었습니다.
문제 3은 주어진 매개변수만큼 for 반복문을 돌며 i를 문자열로 형변환 시키고,  split을 사용해서  369를 잡아냈습니다. 0%3이 예외로 걸려서 &&연산자로 예외처리했습니다.
> 문제 1 ~ 3 해결 

- programmers/level1/신고-결과-받기/곽성재.js
> ✨ 신고결과받기 문제 해결

- programmers/level1/신고-결과-받기/진가람.js
Set 구조와 Array method chaining을 이용했습니다!
> programmers level1 신고 결과 받기 2가지 방식

- programmers/level1/신고-결과-받기/김민준.js
_중복제거를 위해 Set 자료구조를 이용하였습니다. (쓴김에 Map도 썼습니다.)_
- input으로 들어오는 report에서 한 사람에 대한 중복 신고가 불가능하므로 Set을 이용해 중복 제거
- 중복 제거한 리스트를 저장할 **REPORT_INFO_LIST** Set 선언
- 신고당한 id를 key로 가지고, 신고당한 횟수를 value로 가지는 **REPORTED_CNT** Map 선언
- 신고한 id를 key로 가지고, 받은 메일 횟수를 value로 가지는 **RECEIVED_MAIL_CNT** Map 선언
- [REPORTER, REPORTED]의 id list가 저장되어 있는 REPORT_INFO_LIST를 반복문을 돌면서
- REPORTED_CNT에서 REPORTED의 신고당한 횟수가 k 이상일 경우
- RECEIVED_MAIL_CNT에 REPORTED를 신고한 REPORTER가 받을 메일 횟수 + 1
- id_list를 순회하면서 RECEIVED_MAIL_CNT에 값이 존재한다면 그 값을 반환하고, 아니라면 0을 반환
> ✨ 신고 결과 받기 solving - 김민준

- programmers/level1/성격_유형_검사하기/김은경.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/김은경.js
- 모든 입력값이 숫자인가
- 입력값의 길이가 3 인가
- 중복된 숫자가 있는가
- 게임재시작
- 어플리케이션 종료
　
　
> [숫자야구게임_김은경] working on it..... 

- programmers/level1/성격_유형_검사하기/진가람.js
- 1부터 7까지의 선택지에 따른 점수를 요소로 가진 배열 생성
- 하나의 성격 유형에 대한 점수를 업데이트 및 보관하기 위한 Map 자료구조 초기화
- 인자로 주어지는 survey 배열 요소를 순회하며 각 선택지에 따른 성격 유형 점수 저장
- 두 성격 유형을 가진 4가지 지표를 요소로 가진 배열을 만들고 순회하며 최종 성격 반환하기
> ✨ 프로그래머스 성격 유형 검사하기

- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/App.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/config.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/convertToStr.test.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/game.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/interactiveMode.test.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/matchNumbers.test.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/utils.js
- woowacourse-precourse/javascript-onboarding/week2/javascript-baseball/진가람/validateInput.test.js
콜백 함수는 프로미스로 변경하고 더 세분화할 예정입니다
> ✨ 우아코스 2weeks 과제 프로미스화 및 테스트 코드 작성

- programmers/level1/키패드-누르기/곽성재.js
findCoord 로 좌표를 찾아내고,
좌표값을 기준으로, (x1, y1) (x2, y2)간의 거리는
x1 - x2의 절대값 y1 - y2의 절대값을 더하여 구해줍니다.
> ✨ 키패드누르기 - 곽성재

- programmers/level1/기사단원의-무기/진가람.js
- programmers/level1/햄버거-만들기/진가람.js
naive한 문자열 확인 방법에서 kmp 문자열 방식으로 리팩토링 하였습니다.
가장 오래 걸린 12번 문제 4770.68ms -> 1970.77ms 으로 약 2배 가량 성능이 향상되었습니다.
기본 하위 문자열 탐색 방법의 경우, 2중 반복문으로 인해 O(N * M)의 시간 복잡도를 가집니다.
하지만 KMP 문자열 탐색의 경우 탐색 과정에서 습득한 정보들을 다음 탐색에 사용하면서 O(N + M)의 효율을 보입니다.
> Programmers KMP 문자열 탐색 방법을 이용한 햄버거 만들기

- programmers/level1/햄버거-만들기/곽성재.js
- 처음엔 재귀로 접근하려다가 종료조건을 해결하지 못하여서 1시간 이내에 풀지 못하였습니다.
- 다음엔 배열을 문자열로 전환해서 `replace` 사용해서 풀었으나 시간 초과로 실패했습니다.
> 곽성재 - 햄버거 만들기

- programmers/level1/과일-장수/김민준.js
- programmers/level1/옹알이-(2)/김민준.js
- 발음이 가능한 발음들의 리스트를 생성합니다.
- 해당하는 발음의 인덱스로 모두 치환해줍니다.
- 만약 숫자가 아니거나 연속된 숫자가 있다면 false를 return하고,
- 그 외에는 전부 true를 return합니다.
- filter를 적용해 true값의 개수만 세어주어 return합니다.
---
- 내림 차순으로 정렬 후 m번째마다의 점수를 더해줍니다.
> ✨ 옹알이 (2), 과일 장수

- programmers/level1/과일-장수/진가람.js
- programmers/level1/옹알이-(2)/진가람.js
중복을 가시적으로 확인하기 위해 발음 가능한 단어를 해당 단어의 위치(인덱스)로 치환했습니다.
숫자로 이뤄지지 않았거나, 숫자가 연속한다면 조건에 부합하지 않은 것으로 이를 필터링해서 개수를 구했습니다!
> submit: 옹알이2

- programmers/level1/[1차]-다트-게임/김민준.js
- programmers/level1/콜라-문제/김민준.js
- 현재 score와 전의 score를 저장하는 변수 prevScore, score 선언
- 단순 for 반복문으로 index 참조를 통한 순회를 하면서
- **0부터 9점사이인 점수가 들어왔을때 만약 다음 인덱스의 값이 0이라면 점수가 10이라는 뜻**이므로
- score를 10으로 초기화해주고, 인덱스를 뒤로 한칸 옮겨줌
- 보너스가 붙어있다면 보너스에 해당하는 제곱 연산 처리
- **보너스 뒤에 '*'이 붙어있다면**
- **이미 answer엔 prevScore가 더해져 있기 때문에 prevScore를 한번만 더 더하고,** 현재 score 두배로 한 후 인덱스를 뒤로 한칸 옮겨줌
- 보너스 뒤에 '#'이 붙어있다면
- 현재 score를 음수로 바꿔주고 인덱스를 뒤로 한칸 옮겨줌
- 모두 처리한후 현재 score를 answer에 더해줌
> ✨ [1차] 다트 게임

- programmers/level2/위장/전세원.js
옷 종류별로 몇벌씩  있는지 구한 후, 옷 종류 갯수에 맞춰 조합을 했습니다. 
~~1번 테케에서 런타임 오류가 나서 다른분들처럼 다 안입는 경우만 빼는 식을 사용해서 다시 수정 예정입니다.~~
안입는 경우를 고려해서 다 곱하고 나중에 모두 안입은 경우 -1만 하는 형식으로 바꿨습니다. 
난이도는.. 오래 풀어야 풀 수 있는 수준인것 같습니다.
> ✨위장 - 1번테케 런타임 초과 

- programmers/level2/H-Index/진가람.js
- programmers/level2/위장/진가람.js
동일한 카테고리의 옷은 함께 입을 수 없기에 먼저 해시맵을 통해서 해당 카테고리별 의상 개수를 구했습니다.
그 후 해시맵을 순회하면서 각각의 카테고리별 입을 수 있는 경우의 수 조합을 구하고 이를 결과 값에 곱해주며 답을 찾았습니다.
이때 해당 카테고리의 의상을 입지 않을 경우도 함께 고려했으며, 마지막에 포함된 전체 카테고리를 입지 않는 경우는 제외해주었습니다.
> submit: 위장

- programmers/level2/H-Index/곽성재.js
- programmers/level2/위장/곽성재.js
- 만들수있는 조합의 개수를 어떻게 구하면 좋을지 계속고민해봤는데 잘 나오질 않아 결국 춘구님 아이디어를 가져왔습니다..
> ✨ 위장 - 곽성재

- programmers/level2/[1차]-뉴스-클러스터링/김민준.js
- programmers/level2/게임-맵-최단거리/김민준.js
- programmers/level2/스킬트리/김민준.js
- 2글자씩 자른 **문자열이 알파벳으로만 이루어져있는지 확인하는 함수 isAlphabet()** 선언
- `/^[a-z|A-Z]+$/` 을 이용해 판단
- **문자열을 받아서 두 글자씩 잘라서 반환하는 함수 getTwoLettersList()** 선언
- slice()를 이용해 두 글자씩 잘라가면서 알파벳으로만 이루어져 있다면 반환할 결과값에 push
- **교집합의 길이를 얻는 함수 getIntersection()** 선언
- 두 문자열을 두글자씩 자른 배열을 set으로 합쳐 중복을 제거한 후,
- 위 set을 순회하며 각각의 배열에 현재 요소가 몇개 들어있는지 판단한 후,
- 더 작은값을 결과값에 더해줌
- **합집합의 길이를 얻는 함수 getUnion()** 선언
- 두 문자열을 두글자씩 자른 배열을 set으로 합쳐 중복을 제거한 후,
- 위 set을 순회하며 각각의 배열에 현재 요소가 몇개 들어있는지 판단한 후,
- 더 큰값을 결과값에 더해줌
- BIAS 값을 65536으로 설정후, **union이 0이라면 BIAS를 그대로 return** 해주고,
- **0이 아니라면 주어진 계산식에 따라 계산 후 return** 
---
- 순서에 없는 스킬은 공백으로 치환하기
- ``new Regexp(`[^${skill}]`, 'g');`` 을 이용해서 replace로 스킬 제외 공백으로 치환
- isValid 라는 변수로 중간에 유효하지 않으면 false로 바꾸고 break; (flag 역할)
- isValid가 true라면 answer += 1
---
**BFS를 이용하여 풀이**
- queue에 …
> :sparkles: [1차] 뉴스 클러스터링, 스킬트리, 게임 맵 최단거리

- programmers/level2/H-Index/전세원.js
- programmers/level2/[1차]-뉴스-클러스터링/전세원.js
- programmers/level2/스킬트리/전세원.js
스킬트리  -> skill이 skill_tree에서 쓰였으면 쓰인 인덱스를, 안쓰였으면 50을 대신 넣어주었습니다. 그렇게 index들을 담은 temp라는 객체에서 index만 뽑아서 sort를 시키고 원본 배열이랑 join("")을 통해서 비교했습니다! 원본을 join한것과 sort해서 join한것이 같으면 count +=1을 해주었습니다 
[1차]-뉴스-클러스터링 -> 정규식으로 알파벳만 반환시킨 배열을 만들었습니다. str1배열을 기준으로 순회를 하면서 만약 일치하는 알파벳이 str2에 있으면 ""빈문자열로 바뀌도록 처리해서 중복을 방지했습니다. 
H-Index -> h가 citations.length를 넘을 수 없다는 사실을 활용해 for 반복을 i=1부터 돌렸습니다. 인용횟수가 h번을 넘는 count가 i보다 클때  h= i라는 결론까지 가는데 조금 오래 걸렸습니다.
> [1차] 뉴스 클러스터링 / H-Index / 스킬트리

- programmers/level2/[1차]-프렌즈4블록/김민준.js
_2차원 배열을 오른쪽으로 90도 돌려주는 함수 **rotatae()** 생성
현재 board를 인자로 받아 지워질 개수를 반환하는 함수 **check()** 생성
2*2 블록이라면 board에서 지워주는 함수 **deleteBlock()** 생성_
- board에서 해당 인덱스의 값이 2*2 블록안에 있는 값인지 판단하기 위해 board의 크기와 같은 **Boolean type인 isBlock을 생성**
- board와 isBlock 모두 오른쪽으로 90도 회전
- 처음에 지워지는 개수를 check() 함수로 세주고 deletedCount에 저장
- while문을 통해 계속 반복하면서 deletedCount가 0일때까지, 즉 더이상 지울것이 없을때까지 아래과정 반복
- answer에 지운개수를 더해준다
- deleteBlock() 함수를 통해 지워주고
- 지운다음에 check() 함수를 통해 지운 개수를 받아온다
- answer 반환
> ✨ [1차] 프렌즈4블록

- programmers/level2/[3차]-n진수-게임/진가람.js
- programmers/level2/스킬트리/진가람.js
1. n진법으로 변환한 수 t * m 만큼 나열하기
2. 튜브의 순서 p부터 참가 인원 m의 간격으로 튜브 차례의 숫자 나열하기 (인덱스)
3. 대문자로 치환하기
-----
1. 스킬 트리의 목록을 순회하며 해당 스킬셋만 추출합니다.
2. 그리고 기준 순서와 비교하며 순서가 유효한지 확인합니다.
정규표현식 사용 시 매치되지 않는 경우 OR 연산자를 통해  default 값을 주어 로직에 문제가 없도록 수정하였습니다.
> N진수 게임 & 스킬트리

- programmers/level2/다리를-지나는-트럭/곽성재.js
25line 조건 처리를 왜 해주어야 하는지 고민해보겠습니다...
> ✨ 곽성재- 다리를 지나는 트럭

- programmers/level2/[3차]-파일명-정렬/김민준.js
- programmers/level2/구명보트/김민준.js
- programmers/level2/영어-끝말잇기/김민준.js
_[3차] 파일명 정렬은 라이브로 설명했으므로 생략하겠습니다! 궁금점 comment 주세요!_
- 단어가 몇번씩 나왔는지 저장하는 객체 **countWordObj** 선언
- 주어진 input 에서 맨 앞의 word 먼저 카운팅해서 1로 초기화
- words를 1번 인덱스부터 순회
- 현재 index를 i라 할경우, words[i-1]을 prevWord, words[i]를 currentWord에 저장
- currentWord가 나온 횟수를 countWordObj에서 +1
- 이전의 마지막 문자와 현재의 첫번째 문자가 같지 않거나,
현재 단어가 두번 이상 나온 단어일경우
- 번호와 차례를 구해준 후 바로 break
> [3차] 파일명 정렬, 영어 끝말잇기

- programmers/level2/[3차]-파일명-정렬/곽성재.js
```js
function splitToThree(str) {
const reg = /\d+/;
const idx = str.match(reg).index;
const HEAD = str.substring(0, idx);
const NUMBER = str.match(reg)[0];
// 기존
const TAIL = str.substring(str.indexOf(NUMBER[NUMBER.length - 1]) + 1, str.length);
// 변경
const TAIL = str.substring(idx + NUMBER.length, str.length);
return [HEAD, NUMBER, TAIL];
}
```
`idx`가 제가 원하는 `NUMBER`뭉탱이의 처음 숫자의 인덱스를 반환하는 것은 맞았으나, `str.indexOf(NUMBER[NUMBER.length - 1])`이런식으로 숫자 뭉탱이의 마지막 숫자의 인덱스를 찾는 방법이 틀린것을 발견했습니다...!
`0000`같은 연속된 숫자라면 잘못 반환하게 되어서 틀렸던것 같습니다. 예제로 주어진 테케는 전부 같은숫자가 연속으로 나온 케이스가 없어서 잘 통과하였던 것 같습니다.
따라서 기존 방식이 아닌 원하는 숫자 뭉탱이의 첫번째 숫자 인덱스에서 그 뭉탱이의  길이만큼을 더해주면 제가 원하는 `TAIL`부분의 시작 인덱스를 알 수 있어서 통과하였습니다.
여담으로 가장 긴 시간이 걸리는것은 `4.86ms`이네요
> ⚡️ 파일명정렬-곽성재

- programmers/level2/괄호-회전하기/전세원.js
먼저 "{{{" 이런 경우를 판별하기 위해 갯수로 옳은 괄호인지 countBracket 함수를 통해 판별했습니다.
그러고 "{[(]})" 이런 경우를 판별하기 위해 순서가 옳은 괄호인지 orderBracket 함수로 판별했습니다.
왼쪽으로 하나씩 뒤로 보내는것은 splice를 이용했습니다.
> :sparkles: 괄호 회전하기

- programmers/level1/실패율/전세원.js
.toFixed() 메서드 사용시 1~20까지 사용할 수 있다는 사실을 알게 된 문제입니다•
> :sparkles: 실패율

- BOJ/Graph/2178_곽성재.js
민준님 코드를 참고해서 제 코드를 수정했는데,
시간초과가 왜 뜨는지 잘 모르겠네요 ㅎㅎㅎ
참고해서 바꾼사항들은 아래와 같습니다
- 기존에 queue에 [nextY, nextX, m + 1]을 넘겨주는 방식에서(m은 이동횟수) 아예 새로운 cnt 이중배열을 만들어서 횟수를 카운트 합니다
- while문 상단에서 방문처리를 하던 것에서 for loop 내부에서 다음 y,x를 방문처리합니다
- const [nextY, nextX] = [curY + dy, curX + dx]를 그냥 할당문으로 변경
- if 분기처리를 통과하면 큐에 푸쉬하던걸, 분기처리시 컨티뉴를 걸고 하단에서 푸시합니다
- 카운트 이중배열의 N M번째수를 출력합니다
> ✨ BOJ 2178 미로탐색 곽성재
